# Generated by Django 2.1.7 on 2019-04-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_thing_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
