# Generated by Django 3.0.1 on 2020-03-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
