# Generated by Django 2.0.5 on 2019-01-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='nickname',
            new_name='title',
        ),
    ]
