# Generated by Django 2.0.5 on 2019-01-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190120_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='title',
            new_name='nickname',
        ),
    ]
