# Generated by Django 2.0.5 on 2019-01-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(help_text='The Checksum of the File.', max_length=64, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(help_text='The Checksum of the File.', max_length=64)),
                ('location', models.CharField(help_text='The location of this file if it is not a blob', max_length=1024)),
                ('deleted', models.BooleanField(default=False)),
                ('contenttype', models.CharField(help_text='The MIMEType of the file when first uploaded', max_length=256)),
                ('name', models.CharField(help_text='The name of the file when first uploaded.', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField(null=True)),
                ('json', models.TextField()),
                ('application', models.CharField(help_text='The application that created this file', max_length=256)),
                ('applicationkey', models.IntegerField(help_text='A key within that application')),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blobs.Blob')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('sha256', 'application', 'applicationkey')},
        ),
    ]
